# -*- coding: utf-8 -*-
"""Ch3-SimpleRAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7R8UyIFXakWMD2d_SfSPUuVD3ErgV4c
"""

!pip install faiss-cpu

"""## Understanding the Notebook: Core Concepts for AI/ML Engineers

This notebook demonstrates a powerful pattern called **Retrieval Augmented Generation (RAG)**, which combines the strengths of information retrieval with large language models (LLMs). It also introduces different ways to generate **embeddings**, which are fundamental to semantic search and many other AI/ML tasks.

Let's break down the key sections:

### 1. Setting up the Environment and API Keys

*(Refer to cells `dByA1rKQ7CuD`, `Qpr91v_B7dLj`, `RLgRDHEe7wPG`, `duqnyOAA781N`)*

*   **`!pip install faiss-cpu`**: Installs `FAISS` (Facebook AI Similarity Search), an open-source library for efficient similarity search and clustering of dense vectors. It's crucial for quickly finding similar embeddings in large datasets.
*   **`import` statements**: Load necessary libraries like `numpy` for numerical operations, `os` for environment variables, `faiss` for vector search, and `openai` for interacting with OpenAI's models.
*   **API Key Loading**: Your OpenAI API key is loaded from `.env` file using `dotenv` and then made available to the `OpenAI` client. This is a common practice for securely managing sensitive credentials.
*   **Initial LLM Call**: The notebook starts with a basic call to `gpt-4o-mini` to show its limitations regarding real-time information, setting the stage for why RAG is useful.

### 2. Embeddings and Semantic Search with OpenAI and FAISS

*(Refer to cells `CPs-E24G8Vwf` to `tjp6i-08-gTI`)*

At the heart of this section are **embeddings**:

*   **What are Embeddings?** Embeddings are numerical representations (lists of numbers or vectors) of text, images, or other data. The key idea is that items with similar meanings or properties will have embeddings that are numerically 'close' to each other in a high-dimensional space. The `text-embedding-ada-002` model from OpenAI generates these embeddings.

*   **`documents`**: A simple list of strings, which act as our knowledge base.

*   **`get_embeddings(text)` function**: This function takes a piece of text and uses the OpenAI API to convert it into a numerical vector (its embedding).

*   **`doc_embeddings`**: Each document in our `documents` list is converted into its embedding. You can see the `embedding_dim` (dimension of the vector) is 1536, meaning each document is represented by 1536 numbers.

*   **`faiss.IndexFlatL2`**: This creates a FAISS index. `IndexFlatL2` means it's a brute-force index that calculates the L2 (Euclidean) distance between vectors to find the closest ones. It's initialized with the `embedding_dim`.

*   **`index.add(np.array(doc_embeddings).astype('float32'))`**: The embeddings of our documents are added to the FAISS index. FAISS requires the embeddings to be in a NumPy array of `float32` data type.

*   **`retrive_similar_docs(query, k=2)` function**: This function takes a user `query`, converts it into an embedding, and then uses the FAISS `index.search` method to find the `k` most similar document embeddings from our index. It returns the original documents corresponding to those similar embeddings.

### 3. Retrieval Augmented Generation (RAG)

*(Refer to cells `LYTzSHtE_Lk4` to `YpCX9n7mBS2T`)*

This section showcases the RAG pattern:

*   **User Query (`user_query`)**: The user asks a question, for example, "Where is the Eiffel Tower located?"

*   **Retrieval (`retrieved_docs`)**: Instead of directly asking the LLM, the `retrive_similar_docs` function (using embeddings and FAISS) finds the most relevant documents from our knowledge base (e.g., "The Eiffel Tower is in Hyderabad"). This simulates retrieving relevant information from a much larger corpus.

*   **Context Building**: The `retrieved_docs` are then combined to form a `context` string. This context is crucial because it provides the LLM with factual, up-to-date, or domain-specific information that it might not have in its training data.

*   **`generate_response(query, context_docs)` function**: This function takes the original `query` and the `context` (retrieved documents) and constructs a prompt for the LLM. The prompt explicitly asks the LLM to "Answer the question based on the context below."

*   **LLM Generation**: The LLM (`gpt-5` in the function definition, though `gpt-4o-mini` was used in the initial example) then generates a response *constrained by the provided context*. This significantly reduces the chances of the LLM hallucinating or providing outdated information, as it relies on the factual context provided by the retrieval step.

**Application**: RAG is vital for building accurate and reliable AI assistants, chatbots, and knowledge retrieval systems, especially when dealing with proprietary data, rapidly changing information, or when LLMs need to cite their sources.

### 4. Exploring Alternative Embedding Models: Cohere and Hugging Face

*(Refer to cells `6M7VTIKpDlKS` to `7cssw82ZE-b9`)*

This part of the notebook introduces other popular options for generating text embeddings:

*   **`!pip install cohere`**: Installs the Cohere Python SDK.
*   **Cohere Embeddings**: Similar to OpenAI, Cohere provides its own powerful embedding models (e.g., `small`, `embed-english-v3.0`). The `get_embed_cohere` function demonstrates how to use the Cohere client to obtain embeddings for text.

*   **`SentenceTransformer` (Hugging Face)**: This library allows you to easily use pre-trained transformer models (like `all-mpnet-base-v2`) from Hugging Face for sentence embeddings. These models are often optimized for semantic similarity tasks and can be run locally or integrated into applications. The notebook shows how to load a `SentenceTransformer` model and encode text to get its embedding.

### Summary

As an aspiring AI/ML Engineer, understanding this notebook provides a solid foundation in:

1.  **Text Embeddings**: The concept of converting text into numerical vectors that capture semantic meaning.
2.  **Vector Databases/Similarity Search**: How tools like FAISS enable efficient searching of these embeddings to find relevant information.
3.  **Retrieval Augmented Generation (RAG)**: A powerful architectural pattern for enhancing LLM responses with external knowledge, making them more accurate and reliable.
4.  **Ecosystem Awareness**: Familiarity with different providers and libraries for embeddings (OpenAI, Cohere, Hugging Face) and vector search (FAISS).

These are essential skills for building advanced AI applications today!

### Explanation of Cell `Qpr91v_B7dLj`:

```python
import numpy as np
import os
import faiss
import openai
from openai import OpenAI
from dotenv import load_dotenv
load_dotenv()
```

*   **`import numpy as np`**: Imports the `numpy` library, which is fundamental for numerical operations in Python, especially for working with arrays and matrices. It's aliased as `np` for convenience.
*   **`import os`**: Imports the `os` module, which provides a way to interact with the operating system, such as accessing environment variables.
*   **`import faiss`**: Imports the `faiss` library, which we installed in the previous step. This library is used for efficient similarity search among vectors.
*   **`import openai`**: Imports the `openai` library, the official Python client for interacting with OpenAI's API.
*   **`from openai import OpenAI`**: Specifically imports the `OpenAI` client class from the `openai` library. This is the modern way to instantiate the OpenAI client.
*   **`from dotenv import load_dotenv`**: Imports the `load_dotenv` function from the `dotenv` library. This function is used to load environment variables from a `.env` file.
*   **`load_dotenv()`**: Calls the `load_dotenv` function to load environment variables. This is typically used to securely store API keys and other sensitive information outside of your main codebase.

### Explanation of Cell `RLgRDHEe7wPG`:

```python
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_API_KEY
```

*   **`OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')`**: This line retrieves the value of the environment variable named `OPENAI_API_KEY`. The `os.getenv()` function is a standard Python way to access environment variables. This is where the API key loaded by `load_dotenv()` (if present in a `.env` file) would be assigned to the `OPENAI_API_KEY` Python variable.
*   **`OPENAI_API_KEY`**: This line simply prints the value of the `OPENAI_API_KEY` variable to the output of the cell. This is often done to confirm that the API key has been loaded correctly (though for security, one might prefer not to print the full key).

### Explanation of Cell `dByA1rKQ7CuD`:

```python
!pip install faiss-cpu
```

*   **`!pip install faiss-cpu`**: This line uses a shell command (prefixed with `!`) to install the `faiss-cpu` library. FAISS (Facebook AI Similarity Search) is a library for efficient similarity search and clustering of dense vectors. It's essential for quickly finding similar embeddings in large datasets, which is a core part of this notebook's RAG implementation.

### Explanation of Cell `duqnyOAA781N`:

```python
client = OpenAI(api_key=OPENAI_API_KEY)
response = client.chat.completions.create(
  model="gpt-4o-mini",
  messages=[
    {
      "role": "user",
      "content": "can you give me  updates on the current IPL status"
    }
  ]
)
response.choices[0].message.content
```

*   **`client = OpenAI(api_key=OPENAI_API_KEY)`**: This line initializes an `OpenAI` client object. It passes the `OPENAI_API_KEY` (which we loaded in the previous cell) to authenticate with the OpenAI API. This `client` object will be used for all subsequent interactions with OpenAI models.
*   **`response = client.chat.completions.create(...)`**: This is the core call to the OpenAI API to generate a chat completion. We're using the `chat.completions.create` method.
    *   **`model="gpt-4o-mini"`**: Specifies the particular large language model to use for the completion. Here, it's `gpt-4o-mini`.
    *   **`messages=[...]`**: This is a list of message objects that form the conversation history. For a single-turn prompt like this, it contains one message.
        *   **`{"role": "user", "content": "can you give me updates on the current IPL status"}`**: This is the actual user message (prompt) sent to the LLM. The `role` is `"user"` to indicate it's from the user, and `"content"` is the text of the query.
*   **`response.choices[0].message.content`**: After the API call, the `response` object contains the LLM's reply. This line accesses the first (and usually only) choice in the `choices` list, then gets its `message` attribute, and finally extracts the `content` (the actual text) of that message. This output demonstrates the LLM's limitation regarding real-time information, setting the context for why RAG is necessary.

### Explanation of Cell `CPs-E24G8Vwf`:

```python
documents = [

             "The Eiffel Tower is in Hyderabad",
             "Python is popular programming language",
             "OpenAI develops advanced AI models like GPT",
             "The sun rises in the east and sets in the west"

]
```

*   **`documents = [...]`**: This line initializes a Python list named `documents`. This list contains several strings, each representing a short piece of information or a 'document'. In the context of this notebook, these documents serve as our small knowledge base from which the RAG system will retrieve information.

### Explanation of Cell `wCT4v29F9lRk`:

```python
def get_embeddings(text):
  response = client.embeddings.create(
    input=[text],
    model="text-embedding-ada-002"
  )
  return response.data[0].embedding

doc_embeddings = [get_embeddings(doc) for doc in documents]
```

*   **`def get_embeddings(text):`**: This line defines a Python function named `get_embeddings` that takes one argument: `text` (a string).
*   **`response = client.embeddings.create(...)`**: Inside the function, this line makes an API call to OpenAI's embedding service.
    *   **`input=[text]`**: Specifies the text that needs to be embedded. It's passed as a list, even for a single text.
    *   **`model="text-embedding-ada-002"`**: Defines which OpenAI embedding model to use. `text-embedding-ada-002` is a commonly used, cost-effective model for generating embeddings.
*   **`return response.data[0].embedding`**: The API call returns a response object. This line extracts the actual embedding vector from the response. The `data` attribute contains a list of embedding objects, and we take the first one (`[0]`) and then its `embedding` attribute, which is the numerical vector.
*   **`doc_embeddings = [get_embeddings(doc) for doc in documents]`**: This is a list comprehension that applies the `get_embeddings` function to each `doc` (document string) in our `documents` list. The result is a new list called `doc_embeddings`, where each element is the embedding vector for the corresponding document.
"""

import numpy as np
import os
import faiss
import openai
from openai import OpenAI
from dotenv import load_dotenv
load_dotenv()

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_API_KEY

client = OpenAI(api_key=OPENAI_API_KEY)
response = client.chat.completions.create(
  model="gpt-4o-mini",
  messages=[
    {
      "role": "user",
      "content": "can you give me  updates on the current IPL status"
    }
  ]
)
response.choices[0].message.content

documents = [

             "The Eiffel Tower is in Hyderabad",
             "Python is popular programming language",
             "OpenAI develops advanced AI models like GPT",
             "The sun rises in the east and sets in the west"

]

def get_embeddings(text):
  response = openai.Embedding.create(
    input=text,
    model="text-embedding-ada-002"
  )
  return response['data'][0]['embedding']

def get_embeddings(text):
  response = client.embeddings.create(
    input=[text],
    model="text-embedding-ada-002"
  )
  return response.data[0].embedding

doc_embeddings = [get_embeddings(doc) for doc in documents]

len(doc_embeddings)

"""### Explanation of Cell `ksYOIUpW9sjI`:

```python
len(doc_embeddings)
```

*   **`len(doc_embeddings)`**: This line calculates and displays the number of elements in the `doc_embeddings` list. Since `doc_embeddings` holds one embedding vector for each document in our `documents` list, this output simply confirms how many document embeddings were successfully created (in this case, 4).

### Explanation of Cell `EdY525sV95Xe`:

```python
embedding_dim = len(doc_embeddings[0])
embedding_dim
```

*   **`embedding_dim = len(doc_embeddings[0])`**: This line calculates the dimension (length) of a single embedding vector. It takes the first embedding from the `doc_embeddings` list (`doc_embeddings[0]`) and uses `len()` to find its length. This value, `1536`, represents how many numbers are used to represent each document semantically.
*   **`embedding_dim`**: This line simply prints the value of the `embedding_dim` variable to the output of the cell, confirming the dimension of the embeddings.

### Explanation of Cell `tjp6i-08-gTI`:

```python
index = faiss.IndexFlatL2(embedding_dim)
index.add(np.array(doc_embeddings).astype('float32'))
```

*   **`index = faiss.IndexFlatL2(embedding_dim)`**: This line creates a FAISS index. `faiss.IndexFlatL2` is a type of index that performs a brute-force search using Euclidean (L2) distance to find the nearest neighbors. It is initialized with `embedding_dim`, which is the dimensionality of our embedding vectors (1536 in this case).
*   **`index.add(np.array(doc_embeddings).astype('float32'))`**: This line adds the `doc_embeddings` (our list of document embeddings) to the FAISS index. FAISS requires the input data to be a NumPy array of `float32` data type, so `np.array(doc_embeddings).astype('float32')` converts our list of embeddings into the required format before adding them to the index.
"""

embedding_dim = len(doc_embeddings[0])
embedding_dim

index = faiss.IndexFlatL2(embedding_dim)
index.add(np.array(doc_embeddings).astype('float32'))

def retrive_similar_docs(query,k=2):
  query_embedding = np.array(get_embeddings(query)).astype('float32').reshape(1,-1)
  distances, indices = index.search(query_embedding, k)
  return [documents[i] for i in indices[0]]

"""### Explanation of Cell `fywjr6ea-lrw`:

```python
def retrive_similar_docs(query,k=2):
  query_embedding = np.array(get_embeddings(query)).astype('float32').reshape(1,-1)
  distances, indices = index.search(query_embedding, k)
  return [documents[i] for i in indices[0]]
```

*   **`def retrive_similar_docs(query,k=2):`**: This defines a function named `retrive_similar_docs` that takes two arguments: `query` (the text query from the user) and `k` (the number of top similar documents to retrieve, defaulting to 2).
*   **`query_embedding = np.array(get_embeddings(query)).astype('float32').reshape(1,-1)`**: This line converts the input `query` into an embedding that FAISS can use:
    *   `get_embeddings(query)`: First, it generates the embedding vector for the `query` using our previously defined `get_embeddings` function.
    *   `np.array(...)`: Converts this list (the embedding vector) into a NumPy array.
    *   `.astype('float32')`: Casts the array elements to `float32` data type, which FAISS requires.
    *   `.reshape(1,-1)`: Reshapes the 1-dimensional embedding vector into a 2-dimensional array with 1 row and as many columns as needed. FAISS's `search` method expects a 2D array of query vectors.
*   **`distances, indices = index.search(query_embedding, k)`**: This is the core FAISS search operation.
    *   `index.search(query_embedding, k)`: It searches the `index` for the `k` closest vectors to the `query_embedding`.
    *   `distances`: Returns a NumPy array of the distances (L2 distances in this case) between the query embedding and the `k` closest document embeddings.
    *   `indices`: Returns a NumPy array of the indices of the `k` closest documents in the original `doc_embeddings` list.
*   **`return [documents[i] for i in indices[0]]`**: This line constructs the list of retrieved documents:
    *   `indices[0]`: The `indices` array will contain a sub-array for each query (in our case, only one query). We take the first sub-array `[0]` to get the indices for our single query.
    *   `[documents[i] for i in indices[0]]`: This is a list comprehension that iterates through the `indices` (e.g., `[0, 3]`) and retrieves the actual document strings from our original `documents` list using these indices. It then returns this list of retrieved document texts.

### Explanation of Cell `58QSExoP_G7u`:

```python
retrive_similar_docs("Eiffel",k=1)
```

*   **`retrive_similar_docs("Eiffel",k=1)`**: This line calls the `retrive_similar_docs` function we just defined. It passes the query string `"Eiffel"` and specifies `k=1`, meaning it should retrieve only the single most similar document from our knowledge base. The output `['The Eiffel Tower is in Hyderabad']` shows that it successfully retrieved the document most relevant to 'Eiffel'.

### Explanation of Cell `LyIV4MiPAfYp`:

```python
user_query = "Where is the Eiffel Tower located?"
retrieved_docs = retrive_similar_docs(user_query)
retrieved_docs
```

*   **`user_query = "Where is the Eiffel Tower located?"`**: This line defines a string variable `user_query` and assigns it a question that a user might ask. This query will be used to demonstrate the Retrieval Augmented Generation (RAG) process by simulating a user's input.
*   **`retrieved_docs = retrive_similar_docs(user_query)`**: This line is crucial for the 'Retrieval' part of RAG. It calls our previously defined `retrive_similar_docs` function, passing the `user_query` to it. Inside that function, the `user_query` is first converted into an embedding, and then that embedding is used to search the FAISS index to find the most semantically similar documents from our original `documents` list. The function returns a list of these retrieved document strings, which are then stored in the `retrieved_docs` variable.
*   **`retrieved_docs`**: This line simply prints the content of the `retrieved_docs` variable to the output. This allows you to see which documents were identified as most relevant to the `user_query` from our small knowledge base. In this specific example, it returns `['The Eiffel Tower is in Hyderabad', 'The sun rises in the east and sets in the west']`. This highlights that the retrieval is based on the content available in the `documents` list, even if that content is factually incorrect in the real world.

### Explanation of Cell `S6SyD78FCIiX`:

```python
user_query="what is capital of india?"
```

*   **`user_query="what is capital of india?"`**: This line reassigns the `user_query` variable with a new question: `"what is capital of india?"`. This is done to prepare for another demonstration of the Retrieval Augmented Generation (RAG) process with a different query.
"""

retrive_similar_docs("Eiffel",k=1)

#Build the Context

user_query = "Where is the Eiffel Tower located?"
retrieved_docs = retrive_similar_docs(user_query)
retrieved_docs

user_query="what is capital of india?"

def generate_response(query,context_docs):
  context = "\n".join(context_docs)
  prompt=f"Answer the question based on the context below :\n\nContext:\n{context}\n\nQuestion:{query}\nAnswer"
  completion = client.chat.completions.create(
    model="gpt-5",
    messages=[
      {
        "role": "user",
        "content": prompt
      }
    ]
  )
  return completion.choices[0].message.content

"""### Explanation of Cell `Pc8HrIzTApyR`:

```python
def generate_response(query,context_docs):
  context = "\n".join(context_docs)
  prompt=f"Answer the question based on the context below :\n\nContext:\n{context}\n\nQuestion:{query}\nAnswer"
  completion = client.chat.completions.create(
    model="gpt-5",
    messages=[
      {
        "role": "user",
        "content": prompt
      }
    ]
  )
  return completion.choices[0].message.content
```

*   **`def generate_response(query,context_docs):`**: This line defines a Python function named `generate_response`. It takes two arguments:
    *   `query`: The original question asked by the user.
    *   `context_docs`: A list of document strings that were retrieved as being relevant to the `query`.

*   **`context = "\n".join(context_docs)`**: This line takes the list of `context_docs` (which are strings) and joins them together into a single large string. Each document is separated by a newline character (`\n`), formatting them into a readable block of text that will serve as the 'context' for the LLM.

*   **`prompt=f"Answer the question based on the context below :\n\nContext:\n{context}\n\nQuestion:{query}\nAnswer"`**: This line constructs the complete prompt that will be sent to the Large Language Model. It uses an f-string for easy formatting:
    *   It clearly instructs the LLM to "Answer the question based on the context below". This is a critical instruction in RAG, guiding the LLM to rely on the provided information rather than its general training knowledge.
    *   It then includes the `context` (the joined `retrieved_docs`) under a 'Context:' heading.
    *   Finally, it includes the original `query` under a 'Question:' heading and prompts for the 'Answer'.

*   **`completion = client.chat.completions.create(...)`**: This is an API call to the OpenAI `client` to generate a chat completion based on the constructed prompt. This is similar to the initial LLM call at the beginning of the notebook.
    *   **`model="gpt-5"`**: Specifies the LLM to use. Note that while this function is defined with 'gpt-5', the example usage in the notebook might use a different model like 'gpt-4o-mini'.
    *   **`messages=[{"role": "user", "content": prompt}]`**: The prompt created in the previous step is passed as a user message to the LLM.

*   **`return completion.choices[0].message.content`**: After the LLM processes the prompt and context, it returns a `completion` object. This line extracts the actual text of the LLM's generated response from this object. Specifically, it gets the `content` of the first `message` within the `choices` attribute.
"""

response = generate_response(user_query,retrieved_docs)
response

"""### Explanation of Cell `YpCX9n7mBS2T`:

```python
response = generate_response(user_query,retrieved_docs)
response
```

*   **`response = generate_response(user_query,retrieved_docs)`**: This line calls the `generate_response` function (defined in the previous cell) with two arguments:
    *   `user_query`: The question that the user initially asked (e.g., "Where is the Eiffel Tower located?").
    *   `retrieved_docs`: The list of documents that were found to be semantically similar to the `user_query` by our `retrive_similar_docs` function.

    The `generate_response` function then constructs a prompt by embedding these `retrieved_docs` as context along with the `user_query`, and sends it to the specified LLM (like 'gpt-5' or 'gpt-4o-mini'). The LLM's answer, which is based on the provided context, is returned and stored in the `response` variable.

*   **`response`**: This line simply prints the content of the `response` variable. This displays the final answer generated by the LLM, augmented by the information retrieved from our knowledge base. In this example, the output `Hyderabad` is a direct consequence of the (factually incorrect) document provided in our `documents` list, illustrating how the LLM is constrained by the given context.
"""

#IL25v7tEu9RLc86vUcAPwclnFuO7ZiGB7PlywrJ8

!pip install cohere

"""### Explanation of Cell `6M7TIKpDlKS`:

```python
!pip install cohere
```

*   **`!pip install cohere`**: This line uses a shell command (prefixed with `!`) to install the `cohere` Python client library. Cohere is another company that provides powerful large language models and embedding models, similar to OpenAI. This installation prepares the environment to use Cohere's services for generating alternative text embeddings, as demonstrated in later cells of the notebook.
"""

from google.colab import userdata
userdata.get('COHERE_KEY')

"""### Explanation of Cell `KaV1XKvWDoei`:

```python
from google.colab import userdata
userdata.get('COHERE_KEY')
```

*   **`from google.colab import userdata`**: This line imports the `userdata` module specifically designed for Google Colab environments. The `userdata` module allows you to securely store and retrieve sensitive information, like API keys, without hardcoding them directly into your notebook. This is a best practice for security and reusability.
*   **`userdata.get('COHERE_KEY')`**: This line calls the `get` method of the `userdata` object to retrieve the value associated with the key `COHERE_KEY`. In Colab, you would typically set this key in the 'Secrets' tab (a key icon on the left sidebar). When executed, it will return the stored API key, which can then be used to initialize the Cohere client.
"""

import cohere
from sentence_transformers import SentenceTransformer

"""### Explanation of Cell `t2ckmTxHD_qr`:

```python
import cohere
from sentence_transformers import SentenceTransformer
```

*   **`import cohere`**: This line imports the `cohere` library, which allows you to interact with Cohere's API services, including their embedding models.
*   **`from sentence_transformers import SentenceTransformer`**: This line imports the `SentenceTransformer` class from the `sentence_transformers` library. This library is part of the Hugging Face ecosystem and provides an easy way to use pre-trained transformer models for generating sentence embeddings locally or in your application.

### Explanation of Cell `1-xFx2OuEFQA`:

```python
text = "Artificial Intelligence is transforming many industries"
```

*   **`text = "Artificial Intelligence is transforming many industries"`**: This line initializes a string variable named `text`. This particular string will be used as input to generate embeddings in the subsequent cells, demonstrating how different embedding models (Cohere and Hugging Face) convert text into numerical representations.
"""

text = "Artificial Intelligence is transforming many industries"

co = cohere.Client(userdata.get('COHERE_KEY'))

"""### Explanation of Cell `DbGkG8n1ErXc`:

```python
co = cohere.Client(userdata.get('COHERE_KEY'))
```

*   **`co = cohere.Client(userdata.get('COHERE_KEY'))`**: This line initializes a `cohere` client object. It creates an instance of Cohere's client, passing in your `COHERE_KEY` (retrieved securely from `userdata.get('COHERE_KEY')` as explained previously). This `co` object will now be used to interact with Cohere's API, specifically for generating embeddings in the subsequent cells.
"""

def get_embed_cohere(text):
  response = co.embed(texts=[text],model="small")
  return response.embeddings[0]

"""### Explanation of Cell `RGpcVonDELfM`:

```python
def get_embed_cohere(text):
  response = co.embed(texts=[text],model="small")
  return response.embeddings[0]
```

*   **`def get_embed_cohere(text):`**: This line defines a Python function named `get_embed_cohere` that takes one argument: `text` (a string).
*   **`response = co.embed(texts=[text],model="small")`**: Inside the function, this line makes an API call to Cohere's embedding service using the `co` client initialized earlier.
    *   **`texts=[text]`**: Specifies the text that needs to be embedded. It's passed as a list, even for a single text.
    *   **`model="small"`**: Defines which Cohere embedding model to use. `small` is one of Cohere's embedding models.
*   **`return response.embeddings[0]`**: The API call returns a response object. This line extracts the actual embedding vector from the response. The `embeddings` attribute contains a list of embedding vectors, and we take the first one (`[0]`) to get the numerical vector for our input text.
"""

cohere_emb = get_embed_cohere(text)
print(f"Cohere Embeddings length :{len(cohere_emb)}")
print(cohere_emb[:5])

"""### Explanation of Cell `Qk4rrqhaEcG1`:

```python
cohere_emb = get_embed_cohere(text)
print(f"Cohere Embeddings length :{len(cohere_emb)}")
print(cohere_emb[:5])
```

*   **`cohere_emb = get_embed_cohere(text)`**: This line calls the `get_embed_cohere` function, passing the `text` variable (which contains "Artificial Intelligence is transforming many industries") to it. The function returns the Cohere embedding for that text, which is then stored in the `cohere_emb` variable.
*   **`print(f"Cohere Embeddings length :{len(cohere_emb)}")`**: This line prints the length (dimensionality) of the generated Cohere embedding. The `small` model from Cohere typically produces embeddings of length 1024.
*   **`print(cohere_emb[:5])`**: This line prints the first 5 elements of the `cohere_emb` vector. This is done to give a glimpse of the numerical representation without printing the entire 1024-dimension vector.
"""

#3Hugging Face

model = SentenceTransformer('all-mpnet-base-v2')
sent_emb = model.encode(text)
print(f"Hugging Face Embeddings length :{len(sent_emb)}")
print(sent_emb[:5])

"""### Explanation of Cell `f3ZGCDoEEoM4`:

```python
#3Hugging Face
```

*   **`#3Hugging Face`**: This is a Python comment. In the context of this notebook, it serves as a descriptive header or section marker, indicating that the following code cells will demonstrate the use of Hugging Face's `SentenceTransformer` library for generating embeddings.

### Explanation of Cell `7cssw82ZE-b9`:

```python
model = SentenceTransformer('all-mpnet-base-v2')
sent_emb = model.encode(text)
print(f"Hugging Face Embeddings length :{len(sent_emb)}")
print(sent_emb[:5])
```

*   **`model = SentenceTransformer('all-mpnet-base-v2')`**: This line initializes a `SentenceTransformer` model. It downloads and loads a pre-trained model named `'all-mpnet-base-v2'` from the Hugging Face model hub. This model is designed to produce sentence embeddings.
*   **`sent_emb = model.encode(text)`**: This line takes our previously defined `text` variable ("Artificial Intelligence is transforming many industries") and uses the loaded `SentenceTransformer` model to encode it into an embedding vector. The resulting embedding is stored in the `sent_emb` variable.
*   **`print(f"Hugging Face Embeddings length :{len(sent_emb)}")`**: This line prints the length (dimensionality) of the generated Hugging Face embedding. For the `'all-mpnet-base-v2'` model, the embeddings typically have a length of 768.
*   **`print(sent_emb[:5])`**: This line prints the first 5 elements of the `sent_emb` vector, providing a glimpse of the numerical representation without displaying the entire vector.

# RAG-with-VectorDB-and-MultiEmbeddings

## Retrieval Augmented Generation (RAG) with Vector Databases and Multiple Embedding Models

This repository contains a Google Colab notebook demonstrating the core concepts and application of **Retrieval Augmented Generation (RAG)**. RAG is a powerful technique that combines information retrieval with Large Language Models (LLMs) to enhance their responses with up-to-date and factual external knowledge.

## Overview

In this notebook, we explore:

1.  **Text Embeddings**: The fundamental concept of converting text into numerical vectors that capture semantic meaning. We demonstrate this using:
    *   **OpenAI's `text-embedding-ada-002`**
    *   **Cohere's embedding models**
    *   **Hugging Face's `SentenceTransformer` models** (e.g., `all-mpnet-base-v2`)
2.  **Vector Databases/Similarity Search**: How libraries like **FAISS (Facebook AI Similarity Search)** enable efficient storage and retrieval of these high-dimensional embedding vectors to find relevant information quickly.
3.  **Retrieval Augmented Generation (RAG) Pattern**: We implement an end-to-end RAG system where:
    *   A user query is first embedded.
    *   This query embedding is used to retrieve semantically similar documents from a FAISS index.
    *   The retrieved documents (their original text content) are then provided as context to an LLM (e.g., OpenAI's `gpt-4o-mini`) to generate a more accurate, grounded, and informed response, mitigating issues like hallucination.

This notebook is ideal for aspiring AI/ML Engineers looking to build a solid foundation in modern NLP and Generative AI applications.

## Setup and Installation

To run this notebook, you'll need Python and `pip` installed. It's recommended to run this in a Google Colab environment for ease of setup and access to GPUs (though FAISS CPU is used here).

1.  **Clone the repository (if applicable) or open the notebook in Google Colab.**
2.  **Install necessary libraries:**
    ```bash
    !pip install faiss-cpu openai python-dotenv cohere sentence-transformers numpy
    ```

3.  **API Key Configuration:**
    *   **OpenAI**: Obtain an OpenAI API key. Store it securely in a `.env` file in the same directory as your notebook (e.g., `OPENAI_API_KEY="sk-..."`). The notebook uses `dotenv` to load this key.
    *   **Cohere**: Obtain a Cohere API key. In Google Colab, it's recommended to store this key in Colab's built-in **Secrets** manager (click the '🔑' icon on the left panel, add a new secret named `COHERE_KEY`). The notebook accesses this using `from google.colab import userdata`.

## Usage

Once the environment is set up and API keys are configured, simply run through the cells in the notebook sequentially.

The notebook flow is as follows:

1.  **Environment Setup**: Installs libraries and loads API keys.
2.  **Initial LLM Interaction**: Demonstrates an LLM's limitations without external knowledge.
3.  **OpenAI Embeddings & FAISS**: Generates embeddings for sample documents, builds a FAISS index, and performs semantic search.
4.  **RAG Implementation**: Combines retrieval (using embeddings + FAISS) with LLM generation to answer questions based on provided context.
5.  **Alternative Embeddings**: Shows how to use Cohere and Hugging Face `SentenceTransformer` models to generate embeddings.

Experiment with different queries and observe how the RAG system retrieves relevant information and uses it to formulate responses.
"""